package com.habitTracker.backend;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller // This means that this class is a Controller
@RequestMapping(path="/froget") // This means URL's start with /demo (after Application path)
public class MainController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private UserRepository userRepository;

  @Autowired
  private HabitRepository habitRepository;

  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody String addNewUser (@RequestParam String username,
                                          @RequestParam String email,
                                          @RequestParam String password) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    User n = new User();
    n.setName(username);
    n.setEmail(email);
    n.setPassword(password);
    userRepository.save(n);
    return "New user added";
  }

  @PostMapping(path="/addHabit")
  public @ResponseBody String addNewHabit (@RequestParam String habit_name,
                                           @RequestParam String habit_desc,
                                           @RequestParam String icon,
                                           @RequestParam String color,
                                           @RequestParam String habit_type,
                                           @RequestParam String goal,
                                           @RequestParam String start_date,
                                           @RequestParam String end_date) {
    Habit h = new Habit();
    h.setHabit_name(habit_name);
    h.setHabit_desc(habit_desc);
    h.setIcon(icon);
    h.setColor(color);
    h.setHabit_type(habit_type);
    h.setGoal(goal);
    h.setStartDate(start_date);
    h.setEndDate(end_date);
    habitRepository.save(h);
    return "Habit saved";
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<User> getAllUsers() {
    // This returns a JSON or XML with the users
    return userRepository.findAll();
  }

  @GetMapping(path="/allHabits")
  public @ResponseBody Iterable<Habit> getAllHabits() {
    return habitRepository.findAll();
  }

}
